#!/bin/bash
    IFACE=$1
    [ "${IFACE}" = "" ] && IFACE=usb0
    [ -e /sys/class/net/${IFACE} ] || \
    { echo "${IFACE} doesn't exist !!!"; exit 1; }

    NEED_UP=0
    ifquery --state ${IFACE} > /dev/null || NEED_UP=1

    [ "${NEED_UP}" = "1" ] && ifup ${IFACE}
    ifconfig ${IFACE}
    sleep 2

    DEST='220.233.12.1'
    ifconfig ${IFACE} | grep -q ' inet6 2' && \
    DEST='2406:3400:202:8991:5278:b3ff:feab:334d'
    echo "Ping target = ${DEST}"

#    ncat 220.233.12.1 80 > /dev/null &
#    TELNET_PID=$!

    COUNT=0
    while true ; do
#      ps ${TELNET_PID} > /dev/null || break
      ping -c1 -I${IFACE} ${DEST} > /dev/null
      [ $? != 0 ] && break
      (( COUNT += 1 ))
      echo -e -n "\rcount = ${COUNT} "
      sleep 60
    done

#    ps ${TELNET_PID} > /dev/null && kill ${TELNET_PID}

    echo ""
    ifconfig ${IFACE}
    [ "{$NEED_UP}" = "1" ] && ifdown ${IFACE}
    echo "pings = ${COUNT}"

    exit
